## 📌 What is NumPy?

**NumPy (Numerical Python)** is a Python library used for **working with numbers and arrays**.

 Think of NumPy as **fast math with arrays**.

---

## 🧠 Why do we need NumPy?

Normal Python lists:
- Are slow for large calculations
- Need loops for math operations

NumPy:
- Makes calculations **faster**
- Makes code **short and easy**
- Is widely used in **data analysis**
- Numpy Array (NdArray) -> collection of homogeneous items (of same datatype)
---

## 🗂️ Key Points about NumPy

- Used for **working with arrays**
- Makes **data analysis** easy
- Very fast because it is written in **C / C++**
- **Open-source** and **free to use**
- Created in **2005** by **Travis Oliphant**

---

## 📊 Where is NumPy used?

NumPy is used in:
- Data Analysis
- Data Science
- Machine Learning
- Artificial Intelligence

In [ ]:
!pip install numpy

In [1]:
import numpy as np
np.__version__

'2.3.5'

In [ ]:
#ndarray calss in Numpy

In [2]:
help(np.ndarray) 

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any 

## Creating Arrays

In [4]:
arr = np.array([10, 20, 30, 40])
print(arr) # looks like list but is numpy array.Shows the value
print(type(arr)) #ndarray--> n dimentional array. Ndarray is the class
arr #arr shows the representation of the object.
arr.ndim

[10 20 30 40]
<class 'numpy.ndarray'>


1

In [11]:
# 2D array
b = np.array([[1,2,3.2],['4',5,6]] , dtype='int32') #explicitly forced the data type:
print(b) #shows the value,
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [16]:
# What if you REMOVE dtype='float32'?
b = np.array([[1,2,3.2],['4',5,6]])
print(b)  # why? Because NumPy converts everything to string to keep data consistent.

[['1' '2' '3.2']
 ['4' '5' '6']]


In [13]:
print("ndim:", b.ndim)

ndim: 2


##  Array Attributes

In [14]:

print("ndim:", b.ndim) #ndim is attribute of ndarray class
print("shape:", b.shape)
print("size:", b.size)
print("dtype:", b.dtype)


ndim: 2
shape: (2, 3)
size: 6
dtype: <U32


In [17]:
#save the marks of 3 students in 3 subjects
marks = np.array([
    [90, 85, 88], #Ravi
    [100, 98, 100], #aryan
    [33, 56, 90] #keya
])
marks
print("Dim:", marks.ndim)
print("Shape:", marks.shape)

Dim: 2
Shape: (3, 3)


In [18]:
#3 dimensions-> 3 students
#4 subject
#3 exam scores
marks_3d = np.array([
    [
        [20, 30, 56], #math
        [56, 89, 100], #science
        [100, 100, 100], #english
        [100, 100, 100] #French
    ],
    [
        [34, 78, 90], #math
        [45, 67, 90], #science
        [55, 89, 100], #english
        [100, 100, 100] #French
    ],
    [
        [34, 78, 90], #math
        [45, 67, 90], #science
        [55, 89, 100], #english
        [100, 100, 100] #French
    ]
])
marks_3d
print("Shape:", marks_3d.shape)
print("Dim:", marks_3d.ndim)

Shape: (3, 4, 3)
Dim: 3


In [19]:
# Create a array which holds marks of 4 students in 3 subjects and 2 terms

#1st dim -> 4 students
#2nd dim -> term -> 2
#3rd dim -> subject -> 3 subjects

#marks secured by 2nd sudent in 2nd term in 2nd (english) subject

nar = np.array([[ [1, 1, 4] ,[3, 5, 6] ], [ [4,5,7] ,[9,9,0] ], [ [8,6,7],[4,5,5] ], [ [2,4,6], [4,6,0] ] ])
print("Dim:", nar.ndim)
print("Shape:", nar.shape)

Dim: 3
Shape: (4, 2, 3)


##  Special Arrays

In [22]:
#np.array
n1 = np.zeros((2,3))
print(n1)
n2 = np.ones((2,3))
print(n2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


## Indexing & Slicing

In [23]:
arr = np.array([10,20,30,40,50])
arr[2:] #fetch items from index 2 

array([30, 40, 50])

In [39]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]]) # marks  of 3 students in 3 subjects [Maths, English, Science]
mat[0:2] #1st dim -> index 0 to 2 [0 and 1] #marks of 1st 2 student

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a = mat[2, 1] #marks of 3rd student in english
print(a)

8


In [41]:
b = mat[0][2]
print(b)

3


In [42]:
mat[0:2, 1:3] #1st dim -> index 0 to 2 [0 and 1] #2nd dim -> index 1 to 3 [1 and 2]

array([[2, 3],
       [5, 6]])

In [38]:
mat.shape

(3, 3)

##  Vectorized Operations
Vectorized operations mean doing calculations on an entire array at once, without writing loops.

In [43]:
##List
nums = [1, 3, 5]

nums = [x * x for x in nums]

print(nums)


[1, 9, 25]


In [44]:
a = np.array([1,2,3]) #marks of 3 students in Maths
b = np.array([4,5,6]) #marks of 3 students in Science
#total marks of students in the 2 subjects
a + b

array([5, 7, 9])

In [45]:
a * b

array([ 4, 10, 18])

In [46]:
a ** b

array([  1,  32, 729])

In [47]:
a*a

array([1, 4, 9])

##  Aggregation Functions

In [48]:
data = np.array([[1,2,3],[4,5,6]]) #2dim
data.sum()

np.int64(21)

In [49]:
data.sum(axis =0) #returns the sum of each column in the array.
                  # (no studnet info...total marks of students in 3 subject)

array([5, 7, 9])

In [50]:
data.sum(axis =1)#2nd dimension (no subject info...total marks of each student)

array([ 6, 15])

In [51]:
data.mean() # mean is average

np.float64(3.5)

## Performance: NumPy vs Python List

In [52]:
import time

lst = list(range(1_000_000)) #list 
# underscores in numeric literals are ignored by the interpreter. They are only there to make big numbers easier to read.
start = time.time()
[x*x for x in lst] #squaring all the items of the list

print("Python list:", time.time()-start)

arr = np.arange(1_000_000) #numpy array
start = time.time()
arr**2 #element wise operation
print("NumPy:", time.time()-start)


Python list: 0.13096189498901367
NumPy: 0.005311012268066406
