In [1]:
import numpy as np
np.__version__

'2.3.5'

In [11]:
arr = np.array([[2,3,5], [1,2,3]])
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)

[[2 3 5]
 [1 2 3]]
2
6
int64
(2, 3)


In [16]:
print(arr[1:])

[[1 2 3]]


In [34]:
arr = np.array([[ 
                 [2,3,5], 
                 [1,2,3],
                 [5,6,7],
                 [6,8,6]
                ],
                 [ 
                 [20,30,50], 
                 [10,20,30],
                 [50,60,70],
                 [60,80,60]
               ]
            
          ])
print(arr)

[[[ 2  3  5]
  [ 1  2  3]
  [ 5  6  7]
  [ 6  8  6]]

 [[20 30 50]
  [10 20 30]
  [50 60 70]
  [60 80 60]]]


In [43]:
print(arr.shape)
print(arr.ndim)
print(arr[1,1,2])
print(arr[1,1:,1:2])

(2, 4, 3)
3
30
[[20]
 [60]
 [80]]


In [55]:
a = np.array([1,2,3])
b = np.array([6,3,8])

print(a+b)
print(a*b)
print(a**b)
print(b/a)
print(b%a) # reminder


[ 7  5 11]
[ 6  6 24]
[   1    8 6561]
[6.         1.5        2.66666667]
[0 1 2]


In [63]:

a = np.array([[2,2,3],[6,3,8]])
a.sum()

np.int64(24)

In [92]:
a.sum(axis = 0)

array([ 8,  5, 11])

In [65]:
a.sum(axis = 1)

array([ 7, 17])

In [64]:
a.mean()

np.float64(4.0)

In [93]:
import time
# list performance
list = range(1_000_000)

#l = list(range(10))
### 
#print(list)
#print([x for x in list])
###
start = time.time()
# print([x * x for x in list])
[x * x for x in list]
print("list time: " , time.time() - start)


# numpy performance

arr = np.arange(1_000_000)
#print(arr)
start = time.time()
# print(arr * 2)
arr * 2
print("list time: " , time.time() - start)


list time:  0.05070853233337402
list time:  0.0018897056579589844
